### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by JackeyLov5** [shuanx/BurpAPIFinder#3]
师傅有没有想法把 您的两个项目合并呢 我看本身两个功能差别不大 分开的话内存压力太大了 而且重复的工作太浪费时间了
然后建议完全取代hae 要不然两个冲突了 而且hae的修改数据包颜色确实更直观 但是我觉得没人愿意同时保留三个差别不是太大的项目 因为毕竟还有很多漏洞验证的 插件在burp上
最好再把tsojanscan的功能也给加上。。因为作者不更新但是fastjson这类的漏洞利用挺好用的

**Comment by JackeyLov5** [comment]
真得优化一下。师傅
我在测试其他的插件。然后顺手打开了微信的一篇文章，我发现他判断为了后台 然后一直在哪里爆破？更离谱的是我重启了burp这些数据还在。而且还在爆破？这。。
<img width="1464" alt="image" src="https://github.com/shuanx/BurpAPIFinder/assets/130417202/508ed68e-6976-42ea-bb31-b210b471ef79">

<img width="563" alt="image" src="https://github.com/shuanx/BurpAPIFinder/assets/130417202/4ae0c761-bf5c-43c8-9cc3-1e1a38efc4d2">

**Comment by JackeyLov5** [comment]
我觉得关于数据和爆破这里应该快点优化 虽然爆破功能还在开发中 但是输出和写入是很占用资源的 而且还是在建议两个插件合并之前这种太多插件占用资源的情况下

**Comment by shuanx** [comment]
那个只是后台开个一个监听线程而已，直接不输出给你们看就好啦

**Comment by shuanx** [comment]
ApiFinder的定位是敏感信息查找，不会做漏洞探测和利用类，定位不一样。
finderPrint的定位就指纹识别和弱口令爆破。

**Comment by shuanx** [comment]
重启后肯定数据还在，现在就是为了防止闪退才搞的db数据库存储，那个弱口令爆破只是个线程，没有任务就不会去爆破。你也可以关闭掉， 前端都有按钮

**Comment by JackeyLov5** [comment]
> 重启后肯定数据还在，现在就是为了防止闪退才搞的db数据库存储，那个弱口令爆破只是个线程，没有任务就不会去爆破。你也可以关闭掉， 前端都有按钮

每次都要关闭 感觉不优雅，而且 师傅 前面我说的可能您没细看 就是太多插件了 常规漏洞就好几个了。加上hae这种比较显眼的我觉得比较好一样。

**Comment by shuanx** [comment]
这个原本就是为了取代hae，但是常规漏洞还是聚焦指纹识别，不会去搞漏洞探测和利用

**Comment by JackeyLov5** [comment]
> 这个原本就是为了取代hae，但是常规漏洞还是聚焦指纹识别，不会去搞漏洞探测和利用

可是hae的颜色标记好像没有实现呀
