### ISSUE TITLE
爬取页面速度太慢了

### ISSUE THREAD

**Issue by Seeyeah33** [shuanx/BurpAPIFinder#4]
爬取页面速度太慢了，建议优化一下，而且没有进度条，都不知道要等到啥时候，第二天才把页面爬完

**Comment by shuanx** [comment]
这个简单，给你整个进度，目前是3秒爬一个。可以设置成1秒一个

**Comment by Seeyeah33** [comment]
> 这个简单，给你整个细节，目前是3秒爬一个。可以设置成1秒一个
你用过没？哪止3秒一个，一个url爬了我一个钟，快给我来个专属提速
