### ISSUE TITLE
配置 & 结果显示问题

### ISSUE THREAD

**Issue by lufeirider** [shuanx/BurpAPIFinder#8]
1、配置下拉会有重叠的问题（在mac、jdk22、burp v2024.3.1）
2、结构显示，希望增加一列等级，并且可以根据等级显示（因为完全根据正则不可避免产生很多误报，当目标很多时候，直接查看高价值的准确的）

**Comment by shuanx** [comment]
有上角有个高价值的分配，会把比较有价值的和告警准的直接过滤出来
